// Generated by birds:pack; changes invalidate cached exported models.
export const BIRD_ASSET_VERSIONS = {
  "pearl-gull": "7a255f5c3eca7679",
  "lagoon-jay": "a441409e68835695",
  "ember-kestrel": "40e85bfc966a4f26"
} as const;
