import type { CarController } from "../vehicles/car/controller";
import type { SurfTelemetry } from "../vehicles/surf/controller";
import type { FlyController } from "../vehicles/plane/controller";
export const IDLE_LANDING: CarController["landingFeedback"] = Object.freeze({serial:0,height:0,fallDistance:0,strength:0,x:0,y:0,z:0,yaw:0});
export const IDLE_SLIDE: CarController["slideFeedback"] = Object.freeze({blend:0,intensity:0,dir:0,track:0.9,rear:1.6});
export const IDLE_JUMP: CarController["jumpDebug"] = Object.freeze({airborne:false,airTime:0,supportClearance:0,landingSteps:0,readyForTakeoff:true,jumpHeight:0,jumpFallDistance:0,landingSerial:0,landingStrength:0});
export const IDLE_SURF: SurfTelemetry = {
    speed: 0,
    face: 0,
    lip: 0,
    lean: 0,
    grounded: true,
    airborne: false,
    airTime: 0,
    landedAirTime: 0,
    landingSerial: 0,
    assistSerial: 0,
    waveSerial: 0,
    inBreak: true,
    phase: "ride",
    surfaceY: 0,
    clearance: 0,
    lineDirection: 1,
    pump: 0,
    stalling: false,
    faceLine: 0,
    cutbackSerial: 0,
    boardYaw: Math.PI / 2,
    lipReadiness: 0,
    launchSerial: 0,
    splashSerial: 0,
    splashEnergy: 0,
    landingQuality: 1,
    landingCompression: 0,
    flow: 0,
    flowReady: false,
    flowActive: false,
    flowSerial: 0,
    flowTimeRemaining: 0,
    flowRequestBuffered: false,
    riderMotionRate: 1,
    shape: "shortboard",
    crestDistance: 0,
    slopeX: 0,
    slopeZ: 0,
    supportError: 0,
    hullClearance: 0,
    railContact: true,
    relativeFaceSpeed: 0,
    carveInput: 0,
    airSpin: 0,
    landedSpin: 0,
    airFlip: 0,
    landedFlip: 0,
    grabTime: 0,
    landedGrab: 0,
    barrelAhead: 0,
    spitSerial: 0,
    tubeState: "outside",
    tubeDepth: 0,
    tubeCoverage: 0,
    tubeRoofY: 0,
    tubeClearance: 0,
    tubeDwell: 0,
    tubeSerial: 0
  }
export const IDLE_HANG: FlyController["hangGliderTelemetry"] = {
    active: false,
    airspeed: 0,
    verticalSpeed: 0,
    sinkRate: 0,
    lift: 0,
    bank: 0,
    pitch: -0.04,
    altitude: 0,
    stalled: false,
    landed: false,
    touchdownSink: 0,
    touchdownSpeed: 0
  }
export const IDLE_ROCKET: FlyController["rocketTelemetry"] = {
    active: false,
    altitude: 0,
    verticalSpeed: 0,
    speed: 0,
    throttle: 0.58,
    boost: false,
    spaceFactor: 0,
    orbitFactor: 0,
    stage: "launch"
  }
